name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🐛 Bug Fixes'
    labels:
      - 'defect'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  <img src="https://cdn.cnn.com/cnn/2019/images/01/04/logo_color@2x.png" alt="Stellar" width="150"/>

  ## What's Changed

  $CHANGES